update

diff --git a/.github/workflows/Portfolio-API-Deploy.yml b/.github/workflows/Portfolio-API-Deploy.yml
--- a/.github/workflows/Portfolio-API-Deploy.yml
+++ b/.github/workflows/Portfolio-API-Deploy.yml
@@ -61,6 +61,26 @@ jobs:
           files: ${{ inputs.app-name }}-app.zip
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
           tag_name: ${{ inputs.tag }}
+
+      - name: Download github packages
+        uses: robinraju/release-downloader@v1
+        with:
+          repository: ${{ vars.USERNAME }}/${{ inputs.app-name }}
+          tag: ${{ inputs.tag }}
+          fileName: ${{ inputs.app-name }}-app.zip
+          token: ${{ secrets.REPO_ACCESS_TOKEN }}
+          dest: '.' 
+
+      - name: Check if file exists
+        run: |
+          FILE_PATH="./${{ inputs.app-name }}-app.zip"
+          if [ -f "$FILE_PATH" ]; then
+            echo "✅ File '$FILE_PATH' found successfully!"
+            ls -lh "$FILE_PATH" # แสดงข้อมูลไฟล์
+          else
+            echo "❌ Error: File '$FILE_PATH' not found!"
+            exit 1 # ทำให้ step นี้ fail
+          fi     
           
       # - name: Execute remote SSH commands using password
       #   uses: appleboy/ssh-action@v1
